apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    url: http://librecash_victoriametrics:8428
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "1s"
    uid: victoriametrics
